default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly
  # submodules: true

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: ["--config=pyproject.toml"]

  - repo: https://github.com/pycqa/flake8.git
    rev: 4.0.1
    hooks:
    - id: flake8
      args: ["--config=.flake8"]
      additional_dependencies:
        - "flake8-docstrings==1.6.0"